version: "3.8"
services:
    junkserver:
        networks:
            - junk
        ports:
            - 3030:3030
        image: konspirat0r/junkserver
    junkclient:
        networks:
            - junk
        ports:
            - 3000:3000
        image: konspirat0r/junkclient    
networks:
    junk:
        