const carParts = {
    "Engine Parts": [
      "Engine block",
      "Cylinder head",
      "Pistons",
      "Crankshaft",
      "Camshaft",
      "Timing belt/chain",
      "Intake manifold",
      "Exhaust manifold",
      "Carburetor",
      "Fuel injectors",
      "Fuel pump",
      "Oil pump",
      "Water pump",
      "Radiator",
      "Thermostat",
      "Fan",
      "Alternator",
      "Starter motor",
      "Battery"
    ],
    "Drive, Transmission and Steering Parts": [
      "Transmission case",
      "Clutch",
      "Flywheel",
      "Drive shaft",
      "Differential",
      "CV joints",
      "Transmission mount",
      "Power steering pump",
      "Steering column",
      "Steering box",
      "Steering rack",
      "Steering wheel",
      "Wheel bearings",
      "Axle shafts"
    ],
    "Suspension and Brake Parts": [
      "Shock absorbers",
      "Struts",
      "Springs",
      "Control arms",
      "Ball joints",
      "Tie rods",
      "Stabilizer bar",
      "Brake calipers",
      "Brake pads",
      "Brake rotors",
      "Brake lines",
      "Brake master cylinder",
      "Brake booster",
      "Parking brake cable"
    ],
    "Electrical Parts": [
      "Wiring harness",
      "Fuses",
      "Relays",
      "Switches",
      "Sensors",
      "ECU/PCM",
      "Oxygen sensor",
      "Mass air flow sensor",
      "Crankshaft position sensor",
      "Camshaft position sensor",
      "Knock sensor",
      "Throttle position sensor",
      "MAP sensor",
      "Ignition coil",
      "Spark plugs",
      "Distributor cap",
      "Rotor",
      "Ignition module",
      "Voltage regulator"
    ],
    "Body and Chassis Parts": [
      "Hood",
      "Trunk",
      "Fenders",
      "Doors",
      "Quarter panels",
      "Roof",
      "Windshield",
      "Side windows",
      "Rear window",
      "Side mirrors",
      "Rearview mirror",
      "Wiper blades",
      "Wiper motor",
      "Wiper arm",
      "Headlights",
      "Taillights",
      "Brake lights",
      "Turn signal lights",
      "Fog lights",
      "Front bumper",
      "Rear bumper",
      "Front grille",
      "Door handles",
      "Emblems",
      "Moldings",
      "Frame",
      "Chassis",
      "Suspension frame",
      "Fuel tank",
      "Exhaust system",
      "Catalytic converter"
    ]
  };
  